### PR TITLE
Fixed responsive video problems and YouTube JS problems

### PR DESCRIPTION
**Pull request by nicholasgriffintn**
As was referenced on the Wordpress Support page, I have fixed the problems with both videos not being responsive and the problems with Javascript not loading on YouTube videos.

Here is my support topic on Wordpress:

https://wordpress.org/support/topic/youtube-videos-saying-that-javascript-is-not-enabled?replies=3#post-8772869

### CODE REVIEW

**Comment by ahmedkaludi** [comment]
This is amazing! I will review the code in the next week's release cycle and include this in the update with the credit.

Thanks!

**Comment by Asif2BD** [comment]
Just a suggestion @ahmedkaludi , if this pull request does not have a conflict, and as it solves a major problem, can't you merge ASAP, not waiting for next major release. You could release in git at least. WordPress.org plugin release could be weekly.

If anybody need to take this project seriously and use in real important website, those major error and validation issue could be big downside. I understand and support that it's on-going project, but major error like this probably better taken care of ASAP in Git, I mean thats you would use git then svn anyway. Otherwise serious people who want to use this plugin in their reals site need to wait few month maybe to get most stuff sorted and start using when its mostly error free.

I am in love with this project, I appreciate again what you two are doing, this is just a suggestion that we better push stuff that's possible.

**Comment by ahmedkaludi** [comment]
Yes, You are totally right.

I will review this pull request tonight and merge it.

Regards,
Ahmed

**Comment by nicholasgriffintn** [comment]
Awesome, I have simply edited the code from the plugin file myself, so if anyone wants to fix it asap they should do that, it seems to work perfectly fine.

This plugin is definitely great, looking forward to what we can do with it.

**Comment by nicholasgriffintn** [comment]
Sorry, I was working on responsive featured images and accidentally committed to my master, please ignore the previous commits, I will pull the responsive images separately.

**Comment by aashishpahwa** [comment]
Hi 
I'm new to github and coding.
Can anyone tell me how to troubleshoot this?
Where to add this edited code?

**Comment by nicholasgriffintn** [comment]
This code is no longer needed after the most recent update. Thanks for getting that fixed guys :).

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn I really really appreciate your help in this. I am so sorry you did so much work but we couldn't get any of that in the release. I hope that you can contribute in the future release.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi It's perfectly fine, thanks. I was doing it for myself too and I'm definitely going to keep looking into the code, the new update is great, I think using Automatic's AMP plugin as a backing is a much better idea, seems to work a lot better.

Thanks for a cool update.

**Pull request closed without merging**
