### PR TITLE
Update class-amp-gallery-embed.php to enable image captions in galleries

### PR DESCRIPTION
**Pull request by trenzterra**
This pull request adds support for displaying image captions in WordPress galleries. User can style accordingly in CSS by modifying 'i-amp-caption'.

### CODE REVIEW

**Comment by Sejiro-Hiko** [comment]
@trenzterra Thank you so much for your contribution to the community but I cannot Merge this Solution to our Update, Not the way it is now.

I've checked the solution and It does add the Caption to the Gallery but there's need to make lots of changes for improvement of the solution.
Please see below are some Images of the gallery Before and After the solution.
**Before the solution**
kingdom

coffee

**After the solution**
before kingdom

before coffee

As you can see the difference, So, unfortunately, we can't add with the incomplete solution.
If you can provide us the complete solution before 7-Oct-17 we can release it in the upcoming Update.

**Comment by Sejiro-Hiko** [comment]
@trenzterra we've resolved the shading of Images in gallery but there's one more issue with the image resizing (some are getting large ) from their respective size after the Implementation of the solution

**Comment by trenzterra** [comment]
Thank you. For my current installation, I styled the divs using CSS such that the caption will only when the image  has active focus (e.g. when user taps on the image). In addition, I set a max height and adjust overflow and scroll settings so the caption is scrollable. The CSS is easy enough to style so I didn't add it in the merge.

Regarding the image resizing issue, do you have an example? So far I have not encountered this.

**Comment by Sejiro-Hiko** [comment]
@trenzterra thanks for the reply,

Here's the issue I've encountered.
**Before**

before

**After**

after

**Comment by trenzterra** [comment]
What code did you change earlier?

Using the code I committed earlier, and the following CSS, I am able to come to a working solution:

```
.i-amp-caption {
 position: absolute;
      bottom: 20px;
      left: 0;
      right: 0;
      padding: 8px;
      background: rgba(0, 0, 0, 0.6);
      color: #ddd;
      font-size: 0.7em;
      max-height: 30%;
      line-height: 1.3em;
      display: none;
      overflow-y: scroll;
}
```

This solution shows scrollbars on desktop browsers, but on mobile browsers where AMP is targeted no scrollbars show. Note that I am a total novice to PHP. If someone can help me optimise the code, it would be great.


image

Above is the end result from what I have as tested on my website. You can view it here: https://www.describee.com/2017/08/17/capturing-national-day-festivities-fireworks/amp/ (scroll all the way towards the end)

**Comment by ahmedkaludi** [comment]
@trenzterra You can't use the css with -i-amp prefix. Do you have a better solution on tackling this issue?

**Comment by trenzterra** [comment]
@ahmedkaludi We can always rename it to something else, though my page still passes AMP validation notwithstanding this. 

I would like to seek your opinion on two things:
- Should we edit the original amp plugin files this way, which may result in an issue when the original plugin is updated, or do we overwrite it with a class extend instead? On my website I currently overwrite it with a class extend feature in a separate plugin. If so, which file should I place the function in?
- For the custom CSS, if we were to inbuilt it into the plugin, which file should I make the changes to?

As mentioned earlier i am a novice at PHP and CSS. If someone can improve on my solution it would be really helpful.

**Comment by MARQAS** [comment]
@trenzterra Thank you for the solution, but it required static changes in the vendor AMP code, that's why I have solved it in this way to avoid static changes.

**Comment by MohammedKaludi** [comment]
Issue fixed in https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/5fa07c2908d21aa4be6c0b99f56713f356718b58#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4253 and ticket no #1172 so merge is not required and thank you @trenzterra  for the pull request.

Closing the PR. 

Mohammed Kaludi

**Pull request closed without merging**
