### PR TITLE
Added compatibility for Rank Math SEO Plugin

### LINKED ISSUE #2701: Integration with Rank Math SEO
Reference: https://secure.helpscout.net/conversation/719902355/43202?folderId=1060551

### PR DESCRIPTION
**Pull request by MyThemeShop**
Fixed #2701 

Hello,
We wrote the code for the AMP plugin to remove all the conflicts with Rank Math SEO and made it completely compatible.

Once you merge and release the update, we will release an update of Rank Math SEO, removing all the related code.

- `features.php`: Contains all meta tags.
Changes:
https://mythemeshop.d.pr/LrleQH
https://mythemeshop.d.pr/eZd3aX
https://mythemeshop.d.pr/SMoVWO
https://mythemeshop.d.pr/hObV68
https://mythemeshop.d.pr/cJHCl3
https://mythemeshop.d.pr/BNhebd

- `admin-config.php`: Contains an option in Settings to select Rank Math Plugin
Changes: https://mythemeshop.d.pr/8t2E2T

- `amp-post-template-actions.php`: It has the code which removes Snippet data added by AMP plugin when RM is active and Show Rank Math Meta option is selected in Settings.
Changes: https://mythemeshop.d.pr/q7gdoj

Please let us know if you need any changes in the code.

### CODE REVIEW

**Comment by MARQAS** [comment]
Hi @MyThemeShop, thank you so much for the pull request. 
I just reviewed the code, it's very nice. But I believe we can many changes to it. 
1. You wrote the code based on the master branch but we are working on the beta branch i.e., 0.9.98
2. You don't have to add the `do_action( 'rank_math/head' );` hook in our plugin, you can just use `amp_post_template_head` hook and attach your own function to it. You can use like this? `add_action('amp_post_template_head','rank_math/head')`. `amp_post_template_head` runs in the head of every AMP page, so with the help of it, you can add whatever you want to add in the head of an AMP page. 
3. According to the beta/development branch, the option of Rank match in the SEO selection will come at number 6th position.

I tested this plugin a week ago and I was able to find only 2 issues. 
1: 2 structured data ( which I resolved by stopping our structured data when your plugin is active).
2: You are removing the canonical tag from the head of AMP ( By removing one of our function through remove action).
Solutions:
1: I resolved by stopping our structured data when your plugin is active.
2: Instead of removing our function, use the filter to modify the canonicals of AMP. Use this filter `ampforwp_modify_rel_url`. With this filter, you can easily make changes to the canonicals without removing and creating hooks. 

Besides this, the only things which can cause the difference is the title/description of AMP Homepage, Blog and FrontPage. As we are treating them separately than WordPress it can sometimes cause problems. I saw that you made changes to that, can I take that code and commit it by making some necessary changes to it?

**Comment by MARQAS** [comment]
@MyThemeShop, 
I made the necessary changes, there are only 2 things left. 
1. Description of FrontPage and to solve this use the correct ID for AMP FrontPage in your code. I stopped the description from our plugin when Rank math is activated. So use `ampforwp_get_frontpage_id` to get the AMP FrontPage ID. 
2. Canonicals. I see that you are directly removing the hook of canonicals and adding your own. Instead of that, use our filter `ampforwp_modify_rel_url` to modify the canonicals.

**Comment by MyThemeShop** [comment]
Hello @MARQAS 

Sorry for the confusion but we want to make AMP plugin compatible with Rank Math instead of the other way round as that could break things in the future. The PR we created before had an option to select Rank Math plugin in the SEO Settings of your AMP plugin, similar to Yoast & AIO SEO.

Instead of using AMP hooks & filters in the Rank Math SEO plugin we were thinking of adding our SEO code ( Canonical, Snippet & Meta tags ) to your AMP plugin, so the future update of your plugin would not break anything. This will help us keep in sync with the plugin.

Hope that helps. Please let us know how can we help further with that.

Thank you.

**Comment by MARQAS** [comment]
Hi @MyThemeShop, please check this ticket as well https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2701
I have added the option as well.

And regarding the stability, using filters and hooks is more stable than adding that much code of yours in our plugin. 
Let's say in future if you want to change something we have to change the same thing again in our plugin. But that will not the case with hooks and filters. 

And I have almost added everything and left with only 2 or 3 things which I have mentioned in that ticket, please go through that and let me know your thoughts on that.

**Comment by MyThemeShop** [comment]
Also, while testing, please use the attached file as we have removed all the conflicting code from it.
[seo-by-rank-math.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/2695335/seo-by-rank-math.zip)
This version will be released once you update your plugin.

Hope that helps. Thank you.

**Comment by MARQAS** [comment]
Hi @MyThemeShop,
Thank you so much for clearing up all the confusion. I understood clearly now. 
No problem we will add the compatibility code in our plugin only. But for that you have to remove all the code which is related to our plugin otherwise it can cause problems. 
And also please let me know the functions through which I can get 
1.Canonical URL
2.Meta Data
3.Snippet Data
of your plugin.

**Comment by MyThemeShop** [comment]
Hello @MARQAS 

Thank you for your reply.

Sure. Please find the following code to pull the data from the Rank Math plugin:
1) Snippet & Meta Data:
`do_action( 'rank_math/head' );`
2) Canonical URL:
`rank_math()->head->canonical( false );`
To get Title & Description by id:
`RankMath\Post::get_meta( 'title', $ID );`
`RankMath\Post::get_meta( 'description', $post_id );`
3) Schema data is included in the following hook
`do_action('rank_math/head')`
4) You can tick all these options to make the process automated by detecting if Rank Math is active or not by checking it using the following code
`defined( 'RANK_MATH_FILE' )`
5) You can also refer to the following PR which would make things easier
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/2736/commits/e9b1bb407fdc096cf47860b1ab5d4e516decbfa9

Yes, we will remove the code from our plugin as soon as you guys release an update announcing the integration with the Rank Math plugin. WP Rocket recently released an update where they added the complete compatibility with Rank Math.

Please let me know if you need any further information on this. I'm here to help.

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] Imran

**Comment by MyThemeShop** [comment]
Hello @MARQAS

Everything looks good!

Just wanted to confirm if the setting for the Canonical URL is turned on by default and the especially when Rank Math is activated?

Thank you.

**Comment by MARQAS** [comment]
@MyThemeShop We have provided an option in AMP options Panel. if you select Rank Math from the dropdown then all the settings from rank math will reflect in AMP as well

**Comment by beingsmart3** [comment]
- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
Rank Math SEO Plugin compatibility fully added check #2701 for more info
Pushed in 0.9.97.32

**Pull request closed without merging**
