### PR TITLE
A fix to the search box cursor issue that was noted in #1223

### PR DESCRIPTION
**Pull request by nicholasgriffintn**
This is a simple way to fix to search box issue.

Basically, AMP adds a non-scrolling class to the HTML tag when a model is opened, so I am piggybacking off that to set the header to position: fixed when that class is present.

I have tested it with safari and it fixes the issue mentioned but it still needs testing with other browsers and devices.

### CODE REVIEW

**Comment by nicholasgriffintn** [comment]
Don't mind the merge commits, by the way, they are just me updating my fork.

**Comment by MohammedKaludi** [comment]
Thank you for the PR, but this will not be able to merge, because we are not allowed to style i-amp* Elements and also important tag is not valid in amp.

So the page will throw the validation errors. 

Need to find some other class so that we can target to add the Css.

**Comment by nicholasgriffintn** [comment]
@MohammedKaludi Oh yeah, you're right, sorry about that, I completely forgot about that. This might be an issue for the AMP team themselves then maybe? Anything else might be a bit hacky, however, I'll definitely take a look at some hacky options.

**Comment by MohammedKaludi** [comment]
Same here I'm also looking at some other solutions. 
Closing this pull request for now. 

I appreciate your contributions.
Thanks you

**Pull request closed without merging**
