### PR TITLE
fix design 3 header top alignment

### PR DESCRIPTION
**Pull request by ossarchouk**
google search iframe fix

### CODE REVIEW

**Comment by ahmedkaludi** [comment]
Hey, Thank you so much for contributing!

Can you please explain what issue were you having with "google search iframe"?

**Comment by ahmedkaludi** [comment]
Hey Leo @ossarchouk  

Can you please help me understand this one?

**Comment by ossarchouk** [comment]
hi @ahmedkaludi. when google search loads it in iframe you need to set `top:0` in css, 'cuz js top calc dont work properly sometimes. you can see this when you find amp page in google search on some mobile devices or google chrome in mobile testing mode header(design3)

**Comment by ahmedkaludi** [comment]
@MohammedKaludi This is really good one! Please test the pull request from @ossarchouk  and merge it

**Comment by ossarchouk** [comment]
already tested on live project. 
you guys, doing very useful thing 👍. thank you! cheers 
btw, if you have any question about UI stuff like semantics, animations, html/css - just give me a sign

**Comment by MohammedKaludi** [comment]
@ossarchouk Just merged the Pull and Thank you for PR.

**Pull request merged**
