### PR TITLE
0.9.33

### PR DESCRIPTION
**Pull request by Lofesa**
@khaledMohammed000 @ahmedkaludi @MohammedKaludi  If you consider these changes, can be merged

### CODE REVIEW

**Comment by Lofesa** [comment]
Hi @khaledMohammed000 
In this commit I added the do_sorcode() function and supressed the regex to erase Visual Composer shortcodes. With these function all shortcodes inject the html code and the plugins must deal with it. Don´t know how it work whit others shortcodes, they need testing

**Comment by khaledMohammed000** [comment]
Hey @Lofesa 

Please make changes in 

1 . https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/401/commits/e73149f46fc8c832501ff48d68842c377b9f3b69
2.  https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/401/commits/07c3ff11e64d70fbc708d61d82bc0dd66f2b6fac
3. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/401/commits/327751c2a18aaff57a4e0849340dffeda664c177
4. https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/401/commits/3cdcd5eb5a17eb017e538b08bec485f01236ebc5

and then we are good to Merge 👍

**Comment by Lofesa** [comment]
Hi @khaledMohammed000 

Is not a trivial change. Prefechting the sub-resources must be done at each one not in a general call like the preconnect. Example;

`<link rel="prefetch" href="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" >`

and not all those sub-resources are used on all AMP pages.
As far as these sub-resouces belongs on http/2 protocol, when the preconnect is done sub-resources are downloaded as you can test with [webpagetest](https://www.webpagetest.org/) w/o wait to be called in the html and are the 1s thing that are loaded.

**Comment by Lofesa** [comment]
Changed the Disable comment button when comments are disable #393

**Comment by Lofesa** [comment]
Hi @khaledMohammed000 
More on prefecht vs. preconnect
You don´t need dns-prefecht and preconnect. Only one is needed.
Dns-prefecht do dns search before sub-resources are used, preconnect do this plus ssl negotiation and connect stuff and in http/2 it start to download things from the site we do the preconnect stuff before images or any other sub-resource

**Pull request merged**
