### PR TITLE
#2766 Fix unslashed URL

### PR DESCRIPTION
**Pull request by davideprevosto**
When <!- nextpage -> is added for pagination, add the trailingslash if used.

### CODE REVIEW

**Comment by MARQAS** [comment]
Added here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2766

**Comment by pegazee** [comment]
** Review **

- [ ] kaleem

- [ ] imran

**Comment by MohammedKaludi** [comment]
:+1:

**Comment by ahmedkaludi** [comment]
Pushed in 0.9.97.31

**Pull request closed without merging**
