### PR TITLE
validation for session in php

### PR DESCRIPTION
**Pull request by bryan3561**
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1146

### CODE REVIEW

**Comment by MARQAS** [comment]
Hi @bryan3561 
Thank you so much for letting us know this issue and its solution. 
Moving this PR to the Review Board.

**Comment by MARQAS** [comment]
@ahmedkaludi 
It's a Green from my side. 👍

**Comment by ahmedkaludi** [comment]
Thank you @bryan3561 It will be now merged into 0.9.63

**Comment by bryan3561** [comment]
thank you very much, I am very excited to contribute, I would like to contribute more ..

**Pull request merged**
