### PR TITLE
Fix error undefined index fb-instant-page

### PR DESCRIPTION
**Pull request by tpdewolf**
Was getting the following error.

Notice: Undefined index: fb-instant-page-id in /wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4460

### CODE REVIEW

**Comment by ajeetku** [comment]
Already fixed

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by pegazee** [comment]
** Review **

- [ ] Kaleem

- [ ] Imran

**Comment by MohammedKaludi** [comment]
can be improved https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/2610/files/406750e1956115772aaf409b75bbd61a98434c40#diff-6aa5512f7dd8d5ce60fc97b0f340912cR4461

**Comment by MohammedKaludi** [comment]
Pushed in 0.9.97.40
code added here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/713cd6461c2eaf16d9f842e8f3e13fea30bc7d7f

**Pull request closed without merging**
