### PR TITLE
Use util function to get array component. Fixes #3778

### LINKED ISSUE #3778: Warning: preg_match() expects parameter 2 to be string, array given
Wordpress version: 4.6.12
AMP for WP Plugin version: 0.9.98.7

Getting this warning for '/amp' pages: 
Warning: preg_match() expects parameter 2 to be string, array given in /var/www/html/blog/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-tag-and-attribute-sanitizer.php on line 1207

Example: https://pharmeasy.in/blog/can-power-naps-help-you-become-smarter/amp/

Started seeing this error from 5 September and the number of pages affected by this error in Google Search Console has been increasing over time.

Tried deleting the plugin but the '/amp' pages are still available.

### PR DESCRIPTION
**Pull request by heisfullstacked**

### CODE REVIEW

**Comment by heisfullstacked** [comment]
@Zabi09 @ahmedkaludi Can we merge this?

**Comment by ajeetku** [comment]
update vendor log

**Comment by MohammedKaludi** [comment]
Ready to merge.

**Comment by heisfullstacked** [comment]
Do I have to add the vendor log or you guys will add?

**Comment by MohammedKaludi** [comment]
Code pushed in 0.9.98.17 update.

**Pull request merged**
