### PR TITLE
Fixed title output.

### PR DESCRIPTION
**Pull request by sybrew**
Fixes https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/760

1. Removes unused code.
2. Keeps legacy function in place.
3. No longer replaces the title tag.
4. Instead, filters the title tag.
5. Therefore, it works with all SEO plugins.
6. Removed Yoast Compat -- It's no longer needed.
7. Cleaned up code.

## UNTESTED!

Be sure to test it out before including it, both with legacy settings and in combination with SEO plugins (Yoast/AIO/TSF/etc.).

### CODE REVIEW

**Comment by MohammedKaludi** [comment]
@sybrew thank you very much for the PR, I will test it and will get back to you. Planning to push this piece of code in next update, which will be out on 15-April.

Thank you once again for your contribution.
Mohammed Kaludi.

**Comment by sybrew** [comment]
No problem! Do you want me to resolve the branch conflicts? 😄

**Comment by MohammedKaludi** [comment]
@sybrew Yes, please. If you could do that, that would be great.

**Comment by sybrew** [comment]
Done & done! 😄 

FYI: It's still untested. 😅

**Pull request merged**
