### PR TITLE
Enable/Disable pagination and tags section in single

### PR DESCRIPTION
**Pull request by nicholasgriffintn**
Hey,

I noticed in issue #111 that someone was looking for an option to enable/disable the pagination section.

This is something I have already added to my own site, so I figured I would make a quick pull request for it from the code that I already had, it also enables the on/off switch for tags as an added extra.

### CODE REVIEW

**Comment by ahmedkaludi** [comment]
Hey @nicholasgriffintn 

Just a stupid question, but why does the pull request show all previous commits?

It will also merge those commits?

See 
enable disable pagination and tags section in single by nicholasgriffintn pull request 113 ahmedkaludi accelerated mobile pages

**Comment by nicholasgriffintn** [comment]
That's just how Github works strangely, it doesn't allow you to select particular commits, and so you have to push all of them, however, the later commits remove the earlier commits, so anything extra is not included in a merge, just what it says in "Files Changed" section.

You can also "Squash and Merge" to squash all of those commits into a single commit when merging.

screen shot 2016-09-26 at 14 05 10

**Comment by ahmedkaludi** [comment]
@nicholasgriffintn That's strange. Are you sure you can't send a pull request for a specific commit? I think we can do that... right?

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi No unfortunately not, however, those commits have been reverted anyway, if you look at the later commits, I have reverted the changes that I previously made later on. It's because I pushed some commits to my master on accident, really the master should be the same as this version and then it wouldn't be like that, if you merge one though, the other pulls should have the extra commits removed.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi I can reset my master, but that would mean redoing the pulls, if you would prefer to do that, then I can do so later.

**Comment by nicholasgriffintn** [comment]
I have cleaned up the commits in #118 so I am closing this pull for better merging with the new pull.

**Comment by nicholasgriffintn** [comment]
@ahmedkaludi I've re-pulled all of pulls from yesterday for better and cleaner commits, check them out, hopefully that's better for you.

**Pull request closed without merging**
