### PR TITLE
Null check added to fix null reference exception

### PR DESCRIPTION
**Pull request by bishwambharsen**
Null check added to fix null reference exception

### CODE REVIEW

**Comment by MohammedKaludi** [comment]
Thank you @bishwambharsen for the pull request, I'll check it and will get back to you.

**Comment by MohammedKaludi** [comment]
The code will be pushed in the next update.

ETA: 30th September 2018

**Comment by MohammedKaludi** [comment]
Hey @bishwambharsen 

I was reviewing the Pull Request and saw the code you added 
https://github.com/ahmedkaludi/accelerated-mobile-pages/pull/2526/commits/00b33c0812f967fd9dbb248b9cab71ce4aefdba9#diff-9253027ab0fd0dc36f48733d5f042541R91

`! is_null()` is used that will stop the loop and can break the layout.
I think it should be like this `if( is_null($element) ) continue;`

**Comment by bishwambharsen** [comment]
Absolutely correct. It should be is_null. My apologies.

**Comment by MohammedKaludi** [comment]
NO problem, I have merged the code into master. And the code will be pushed in 0.9.97.19 update.

Thank you very much for the contribution. Future pull requests are welcome. 

Code merged in master. Closing the pull request.

**Comment by bishwambharsen** [comment]
Thanks a lot! Happy to help! 😊👍🏻

**Pull request merged**
